import css from "./FrontPage.module.css";
const ShopByCategories = () => {
  return (
    <>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\2.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\2.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\3.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\4.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\5.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\6.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\7.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\8.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\9.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          className={css.ShopByCategoriesItem}
          src="images\categories\10.jpg"
          alt=""
        />
      </div>
    </>
  );
};
export default ShopByCategories;
